// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStepPlugin = "step_plugin"

// StepPlugin 步骤-插件表
type StepPlugin struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	StepID       int32     `gorm:"column:step_id;not null" json:"stepId"`
	PluginID     int32     `gorm:"column:plugin_id;not null" json:"pluginId"`
	Sort         int32     `gorm:"column:sort;not null;comment:标明该插件可以在哪一步骤的哪一阶段使用" json:"sort"`                         // 标明该插件可以在哪一步骤的哪一阶段使用
	CreateTime   time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"createTime"` // 创建时间
	UpdateTime   time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updateTime"` // 更新时间
	CreateUserID string    `gorm:"column:create_user_id;not null;default:系统管理员;comment:创建人" json:"createUserId"`         // 创建人
	UpdateUserID string    `gorm:"column:update_user_id;not null;default:系统管理员;comment:创建人" json:"updateUserId"`         // 创建人
	Extra        *string   `gorm:"column:extra" json:"extra"`
}

// TableName StepPlugin's table name
func (*StepPlugin) TableName() string {
	return TableNameStepPlugin
}
