// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTask = "task"

// Task 任务流表
type Task struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TaskName     string    `gorm:"column:task_name;not null" json:"taskName"`
	Status       int32     `gorm:"column:status;not null;default:1;comment:状态：1创建中、2已完成、-1已删除" json:"status"`            // 状态：1创建中、2已完成、-1已删除
	CreateTime   time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"createTime"` // 创建时间
	UpdateTime   time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updateTime"` // 更新时间
	CreateUserID string    `gorm:"column:create_user_id;not null;default:系统管理员;comment:创建人" json:"createUserId"`         // 创建人
	UpdateUserID string    `gorm:"column:update_user_id;not null;default:系统管理员;comment:创建人" json:"updateUserId"`         // 创建人
	Extra        *string   `gorm:"column:extra" json:"extra"`
	CueWord      *string   `gorm:"column:cue_word;comment:引导词" json:"cueWord"` // 引导词
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
