// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

// Detail mapped from object
type Detail struct {
	Username string `json:"username"` // 用户名
	Age      uint   `json:"age"`      // 用户年龄
	Phone    string `json:"phone"`    // 手机号
}
