// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"encoding/json"
)

const TableNameData = "data"

// Data mapped from table <data>
type Data struct {
	ID       uint     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"` // 主键
	UserInfo []Detail `json:"user_info"`                                                              // 用户信息
	/*
		备注
		详细信息
	*/
	Remark json.RawMessage `gorm:"column:detail" json:"remark"`
}
