// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTaskLog = "task_log"

// TaskLog 任务流日志表
type TaskLog struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID       int32     `gorm:"column:user_id;not null" json:"user_id"`
	TaskID       int32     `gorm:"column:task_id;not null" json:"task_id"`
	TaskLogName  string    `gorm:"column:task_log_name;not null" json:"task_log_name"`
	Input        *string   `gorm:"column:input;comment:输入：wiki地址" json:"input"`                                           // 输入：wiki地址
	IsNamed      bool      `gorm:"column:is_named;not null;comment:是否被手动命名过，没有的话就要存入wiki里面的标题" json:"is_named"`           // 是否被手动命名过，没有的话就要存入wiki里面的标题
	Status       int32     `gorm:"column:status;not null;default:1;comment:该任务流的状态:1创建中、2已完成、-1已删除" json:"status"`        // 该任务流的状态:1创建中、2已完成、-1已删除
	CreateTime   time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime   time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	CreateUserID string    `gorm:"column:create_user_id;not null;default:系统管理员;comment:创建人" json:"create_user_id"`        // 创建人
	UpdateUserID string    `gorm:"column:update_user_id;not null;default:系统管理员;comment:创建人" json:"update_user_id"`        // 创建人
	Extra        *string   `gorm:"column:extra" json:"extra"`
	StepNow      int32     `gorm:"column:step_now;not null;comment:这个任务执行到了哪一步" json:"step_now"` // 这个任务执行到了哪一步
}

// TableName TaskLog's table name
func (*TaskLog) TableName() string {
	return TableNameTaskLog
}
