config:
  apollo:
    appId: huiyin
    cluster: cpf
    endpoint: http://test-apollo-meta.xesv5.com
    namespace: application.json
    backupPath: /Users/caopengfei/work/tal/go-project/huiyin/configs
