// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package test

import (
	"github.com/google/wire"
	"wire_demo/dao"
	"wire_demo/service"
)

// Injectors from wire.go:

func InitDemoService() *service.DemoServiceImpl {
	mockDemoDao := dao.NewMockDemoDao()
	demoServiceImpl := service.NewDemoServiceImpl(mockDemoDao)
	return demoServiceImpl
}

// wire.go:

var Set2 = wire.NewSet(dao.NewMockDemoDao, wire.Bind(new(dao.DemoDao), new(*dao.MockDemoDao)))
