// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
	"wire_demo/controller"
	"wire_demo/dao"
	"wire_demo/service"
)

// Injectors from wire.go:

func InitController() *controller.DemoController {
	demoDaoImpl := dao.NewDemoDaoImpl()
	demoServiceImpl := service.NewDemoServiceImpl(demoDaoImpl)
	userServiceImpl := service.NewUserServiceImpl()
	demoController := controller.NewDemoController(demoServiceImpl, userServiceImpl)
	return demoController
}

// wire.go:

var Set1 = wire.NewSet(service.NewDemoServiceImpl, wire.Bind(new(service.DemoService), new(*service.DemoServiceImpl)))

var Set2 = wire.NewSet(dao.NewDemoDaoImpl, wire.Bind(new(dao.DemoDao), new(*dao.DemoDaoImpl)))

var Set3 = wire.NewSet(service.NewUserServiceImpl, wire.Bind(new(service.IUserService), new(*service.UserServiceImpl)))
